const CONSTANTS = {
    ACCESS_TOKEN_KEY: 'ACCESS_TOKEN_KEY',
    REFRESH_TOKEN_KEY: 'REFRESH_TOKEN_KEY',
    REST_API_URL: 'http://localhost:3001/api/',
    GET_GAME_ROOMS_LIMIT: 10
}

export default CONSTANTS;

