const ACTION_TYPES = {
  AUTH_REQUEST: Symbol(),
  AUTH_SUCCESS: Symbol(),
  AUTH_ERROR: Symbol(),
  CREATE_GAME_ROOM_REQUEST: Symbol(),
  CREATE_GAME_ROOM_SUCCESS: Symbol(),
  CREATE_GAME_ROOM_ERROR: Symbol(),
  GET_ALL_GAME_ROOMS_REQUEST: Symbol(),
  GET_ALL_GAME_ROOMS_SUCCESS: Symbol(),
  GET_ALL_GAME_ROOMS_ERROR: Symbol()
};

export default ACTION_TYPES;