const ACTION_TYPES = {
  AUTH_REQUEST: Symbol(),
  AUTH_SUCCESS: Symbol(),
  AUTH_ERROR: Symbol(),
  CREATE_GAME_ROOM_REQUEST: Symbol(),
  CREATE_GAME_ROOM_SUCCESS: Symbol(),
  CREATE_GAME_ROOM_ERROR: Symbol(),
  GET_GAME_ROOMS_REQUEST: Symbol(),
  GET_GAME_ROOMS_SUCCESS: Symbol(),
  GET_GAME_ROOMS_ERROR: Symbol(),
  JOIN_GAME_ROOM_REQUEST: Symbol(),
  JOIN_GAME_ROOM_SUCCESS: Symbol(),
  JOIN_GAME_ROOM_ERROR: Symbol(),
  CLEAR_AUTH_STORE: Symbol(),
  CLEAR_GAME_STORE: Symbol(),
  CHECK_IS_USER_IN_SOME_ROOM_REQUEST: Symbol(),
  CHECK_IS_USER_IN_SOME_ROOM_SUCCESS: Symbol(),
  CHECK_IS_USER_IN_SOME_ROOM_ERROR: Symbol()
};

export default ACTION_TYPES;